# Generated by Django 5.1 on 2024-08-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('tipo_identificacion', models.CharField(max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_celular', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('ultima_facturacion', models.DateField()),
                ('ultimo_pago', models.IntegerField(default=0)),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente')),
            ],
            options={
                'unique_together': {('identificacion', 'servicio')},
            },
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
